import React from 'react';
import { createRoot } from 'react-dom/client';

const App = () => {
  return     <div>
    <header>
      <h1>Welcome to our Hugo/React website 🚀</h1>
    </header>
    <main>
      <p>This page is generated by React !</p>
    </main>
    <footer>
      <p>React Footer</p>
    </footer>
  </div>;
};

const domNode = document.getElementById('react-root');
const root = createRoot(domNode);
root.render(<App />);
